/**
 * Pure catalog row snapshots shared by seeders and `audit.ts`.
 * Importing this module does **not** open a database connection (unlike `resources.ts`, etc.).
 */
import type { buildingTypes } from '../schema/buildings.js';
import type { resources } from '../schema/resources.js';
import type { shipTypes } from '../schema/ships.js';
import * as resourceExtractionRatesModule from '@shared/config/resourceExtractionRates.js';
import * as buildingUpgradeEconomyModule from '@shared/config/buildingUpgradeEconomy.js';
import type { CombatStats } from '@shared/types/combat.js';

export type ResourceCatalogRow = typeof resources.$inferInsert;
export type BuildingCatalogRow = typeof buildingTypes.$inferInsert;
export type ShipCatalogRow = typeof shipTypes.$inferInsert;

type ResourceExtractionRatesModule = typeof import('@shared/config/resourceExtractionRates.js');
type BuildingUpgradeEconomyModule = typeof import('@shared/config/buildingUpgradeEconomy.js');

// Local `tsx src/db/seed.ts` can expose @shared TS modules through a CJS
// default export, while Vitest/tsc see normal ESM named exports.
const resourceExtractionRatesInterop = resourceExtractionRatesModule as ResourceExtractionRatesModule & {
  default?: ResourceExtractionRatesModule;
};
const buildingUpgradeEconomyInterop = buildingUpgradeEconomyModule as BuildingUpgradeEconomyModule & {
  default?: BuildingUpgradeEconomyModule;
};

const EXTRACTABLE_RESOURCE_RATES_PER_HOUR =
  resourceExtractionRatesInterop.EXTRACTABLE_RESOURCE_RATES_PER_HOUR ??
  resourceExtractionRatesInterop.default!.EXTRACTABLE_RESOURCE_RATES_PER_HOUR;
const MAX_BUILDING_LEVEL =
  buildingUpgradeEconomyInterop.MAX_BUILDING_LEVEL ??
  buildingUpgradeEconomyInterop.default!.MAX_BUILDING_LEVEL;

export const RESOURCE_CATALOG_ROWS: ResourceCatalogRow[] = [
  { id: 'energy', symbol: 'E', tier: 1, name: { ru: 'Энергия', en: 'Energy' }, baseRegenRate: 0, defaultStorageCap: 0 },
  { id: 'water', symbol: 'H₂O', tier: 1, name: { ru: 'Вода', en: 'Water' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.water, defaultStorageCap: 5000 },
  { id: 'iron', symbol: 'Fe', tier: 1, name: { ru: 'Железо', en: 'Iron' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.iron, defaultStorageCap: 5000 },
  { id: 'carbon', symbol: 'C', tier: 1, name: { ru: 'Углерод', en: 'Carbon' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.carbon, defaultStorageCap: 5000 },
  { id: 'silicon', symbol: 'Si', tier: 1, name: { ru: 'Кремний', en: 'Silicon' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.silicon, defaultStorageCap: 5000 },
  { id: 'methane', symbol: 'CH₄', tier: 1, name: { ru: 'Метан', en: 'Methane' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.methane, defaultStorageCap: 5000 },
  { id: 'oxygen', symbol: 'O₂', tier: 1, name: { ru: 'Кислород', en: 'Oxygen' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.oxygen, defaultStorageCap: 5000 },
  { id: 'hydrogen', symbol: 'H₂', tier: 1, name: { ru: 'Водород', en: 'Hydrogen' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.hydrogen, defaultStorageCap: 5000 },
  { id: 'fuel', symbol: 'Fuel', tier: 1, name: { ru: 'Топливо', en: 'Fuel' }, baseRegenRate: 0, defaultStorageCap: 1000 },

  { id: 'copper', symbol: 'Cu', tier: 2, name: { ru: 'Медь', en: 'Copper' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.copper, defaultStorageCap: 2500 },
  { id: 'aluminum', symbol: 'Al', tier: 2, name: { ru: 'Алюминий', en: 'Aluminum' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.aluminum, defaultStorageCap: 2500 },
  { id: 'silver', symbol: 'Ag', tier: 2, name: { ru: 'Серебро', en: 'Silver' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.silver, defaultStorageCap: 2500 },
  { id: 'titanium', symbol: 'Ti', tier: 2, name: { ru: 'Титан', en: 'Titanium' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.titanium, defaultStorageCap: 2500 },
  { id: 'ice', symbol: 'Ice', tier: 2, name: { ru: 'Лёд', en: 'Ice' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.ice, defaultStorageCap: 2500 },
  { id: 'oil', symbol: 'Oil', tier: 2, name: { ru: 'Нефть', en: 'Oil' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.oil, defaultStorageCap: 2500 },
  { id: 'sulfur', symbol: 'S', tier: 2, name: { ru: 'Сера', en: 'Sulfur' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.sulfur, defaultStorageCap: 2500 },
  { id: 'steel', symbol: 'St', tier: 2, name: { ru: 'Сталь', en: 'Steel' }, baseRegenRate: 0, defaultStorageCap: 2500 },
  {
    id: 'electronics',
    symbol: 'EC',
    tier: 2,
    name: { ru: 'Электроника', en: 'Electronics' },
    baseRegenRate: 0,
    defaultStorageCap: 2500,
  },

  { id: 'mercury', symbol: 'Hg', tier: 3, name: { ru: 'Ртуть', en: 'Mercury' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.mercury, defaultStorageCap: 1000 },
  { id: 'magnesium', symbol: 'Mg', tier: 3, name: { ru: 'Магний', en: 'Magnesium' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.magnesium, defaultStorageCap: 1000 },
  { id: 'lead', symbol: 'Pb', tier: 3, name: { ru: 'Свинец', en: 'Lead' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.lead, defaultStorageCap: 1000 },
  { id: 'nitrogen', symbol: 'N₂', tier: 3, name: { ru: 'Азот', en: 'Nitrogen' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.nitrogen, defaultStorageCap: 1000 },
  { id: 'uranium', symbol: 'U', tier: 3, name: { ru: 'Уран', en: 'Uranium' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.uranium, defaultStorageCap: 1000 },
  { id: 'cobalt', symbol: 'Co', tier: 3, name: { ru: 'Кобальт', en: 'Cobalt' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.cobalt, defaultStorageCap: 1000 },
  {
    id: 'silicon_carbide',
    symbol: 'SiC',
    tier: 3,
    name: { ru: 'Карбид кремния', en: 'Silicon Carbide' },
    baseRegenRate: 0,
    defaultStorageCap: 1000,
  },
  { id: 'tritium', symbol: 'T', tier: 3, name: { ru: 'Тритий', en: 'Tritium' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.tritium, defaultStorageCap: 500 },
  { id: 'gold', symbol: 'Au', tier: 3, name: { ru: 'Золото', en: 'Gold' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.gold, defaultStorageCap: 1000 },
  { id: 'jump_fuel', symbol: 'JF', tier: 3, name: { ru: 'Прыжковое топливо', en: 'Jump Fuel' }, baseRegenRate: 0, defaultStorageCap: 500 },

  { id: 'antimatter', symbol: 'Am', tier: 4, name: { ru: 'Антиматерия', en: 'Antimatter' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.antimatter, defaultStorageCap: 100 },
  { id: 'iridium', symbol: 'Ir', tier: 4, name: { ru: 'Иридий', en: 'Iridium' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.iridium, defaultStorageCap: 100 },
  { id: 'biomass', symbol: 'Bio', tier: 4, name: { ru: 'Биомасса', en: 'Biomass' }, baseRegenRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.biomass, defaultStorageCap: 1000 },
  { id: 'liquid_nitrogen', symbol: 'LN₂', tier: 3, name: { ru: 'Жидкий азот', en: 'Liquid Nitrogen' }, baseRegenRate: 0, defaultStorageCap: 1000 },
  { id: 'military_alloy', symbol: 'MA', tier: 3, name: { ru: 'Военный сплав', en: 'Military Alloy' }, baseRegenRate: 0, defaultStorageCap: 1000 },
  { id: 'military_composite', symbol: 'MC', tier: 3, name: { ru: 'Военный композит', en: 'Military Composite' }, baseRegenRate: 0, defaultStorageCap: 1000 },
];

/**
 * Building upgrade economics (backend `BuildingService.upgrade` + `features/buildings/upgrade.ts`):
 * - Cost for upgrading from level L → L+1: `floor(baseCost * 1.6^L)` per resource.
 * - Time: `floor(baseTimeSec * 1.8^L)` before research build-speed modifiers.
 * Initial construction pays listed `baseCost` / `baseTimeSec` without these multipliers.
 */
export const BUILDING_TYPE_CATALOG_ROWS: BuildingCatalogRow[] = [
  {
    id: 'command_center',
    name: { ru: 'Командный центр', en: 'Command Center' },
    description: {
      ru: 'Административный узел вашей колонии. Позволяет строить новые здания.',
      en: 'Administrative hub of your colony. Enables new building construction.',
    },
    category: 'base',
    maxPerPlanet: 1,
    maxGlobal: null,
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [],
    baseCost: { iron: 80, carbon: 40, silicon: 10 },
    baseTimeSec: 600,
    baseOutput: {},
    energyConsumption: 0,
    combatStats: { targetClass: 'command_center' } as CombatStats,
  },
  {
    // Solid-resource surface mine. Pairs with the gases-only `drill` below;
    // the two were previously identical except for output — they are now
    // semantically distinct buildings with different costs, deps and
    // biome affinities.
    id: 'mine',
    name: { ru: 'Шахта', en: 'Mine' },
    description: {
      ru: 'Добывает твёрдые минеральные ресурсы из выбранного местного месторождения.',
      en: 'Extracts solid mineral resources from the selected local deposit.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 1 }],
    // Heavier upfront iron cost reflects building reinforced ore-haulers.
    baseCost: { iron: 120, carbon: 40 },
    baseTimeSec: 300,
    baseOutput: { resourceId: 'iron', baseRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.iron },
    energyConsumption: 10,
  },
  {
    // Gases-only extractor. Water and biomass moved to the bioreactor,
    // while oil/methane hydrocarbon pockets belong to the oil pump.
    id: 'drill',
    name: { ru: 'Газовый экстрактор', en: 'Gas Extractor' },
    description: {
      ru: 'Добывает газы из выбранного местного источника.',
      en: 'Extracts gases from the selected local source.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    // Slightly different gate: needs a tier-1 solar plant (electronics for
    // the condenser) so it cannot trivially overlap the mine.
    deps: [
      { typeId: 'command_center', level: 1 },
      { typeId: 'solar_plant', level: 1 },
    ],
    baseCost: { silicon: 100, carbon: 80 },
    baseTimeSec: 360,
    baseOutput: { resourceId: 'methane', baseRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.methane },
    energyConsumption: 14,
  },
  {
    id: 'storage',
    name: { ru: 'Склад', en: 'Storage' },
    description: {
      ru: 'Увеличивает вместимость хранилищ для всех типов ресурсов на планете.',
      en: 'Increases storage capacity for all types of resources on the planet.',
    },
    category: 'logistics',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 1 }],
    baseCost: { iron: 150, carbon: 50 },
    baseTimeSec: 600,
    baseOutput: { cap: 5000 },
    energyConsumption: 5,
  },
  {
    id: 'battery',
    name: { ru: 'Аккумулятор', en: 'Battery' },
    description: {
      ru: 'Обязательное энергетическое хранилище колонии. Накапливает избыток генерации и питает здания при просадках.',
      en: 'Mandatory colony energy storage. Stores surplus generation and powers buildings during deficits.',
    },
    category: 'energy',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 1 }],
    baseCost: { iron: 120, silicon: 90, carbon: 40 },
    baseTimeSec: 420,
    baseOutput: { energyCap: 500 },
    energyConsumption: 0,
  },
  {
    id: 'oil_pump',
    name: { ru: 'Нефтекачка', en: 'Oil Pump' },
    description: {
      ru: 'Добывает нефть или метан из выбранного местного углеводородного пласта.',
      en: 'Extracts oil or methane from the selected local hydrocarbon reservoir.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 2 }],
    baseCost: { iron: 220, silicon: 140, carbon: 120 },
    baseTimeSec: 720,
    baseOutput: { resourceId: 'oil', baseRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.oil },
    energyConsumption: 12,
  },
  {
    id: 'biomass_harvester',
    name: { ru: 'Биореактор', en: 'Bioreactor' },
    description: {
      ru: 'Поддерживает жизнеобеспечение, добывая воду или культивируя биомассу из местного источника.',
      en: 'Supports life support by extracting water or culturing biomass from the local source.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 2 }],
    baseCost: { iron: 180, carbon: 160, water: 120 },
    baseTimeSec: 840,
    baseOutput: { resourceId: 'biomass', baseRate: EXTRACTABLE_RESOURCE_RATES_PER_HOUR.biomass },
    energyConsumption: 18,
  },
  {
    id: 'smelter',
    name: { ru: 'Завод', en: 'Smelter' },
    description: {
      ru: 'Перерабатывает сырьё в очищенные конструкционные материалы.',
      en: 'Processes raw inputs into refined structural materials.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 3 }],
    baseCost: { iron: 400, silicon: 200 },
    baseTimeSec: 900,
    baseOutput: {},
    energyConsumption: 30,
  },
  {
    id: 'refinery',
    name: { ru: 'Нефтеперерабатывающий завод', en: 'Refinery' },
    description: {
      ru: 'Перерабатывает углеводородное сырьё в корабельное топливо.',
      en: 'Processes hydrocarbon feedstock into ship fuel.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 3 }],
    baseCost: { iron: 550, silicon: 320, steel: 180 },
    baseTimeSec: 1500,
    baseOutput: {},
    energyConsumption: 28,
  },
  {
    id: 'fabrication_bay',
    name: { ru: 'Цех электроники', en: 'Fabrication Bay' },
    description: {
      ru: 'Собирает электронные компоненты из проводников и очищенных материалов.',
      en: 'Assembles electronic components from conductors and refined materials.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 3 }],
    baseCost: { iron: 450, silicon: 350, carbon: 150, steel: 120 },
    baseTimeSec: 1200,
    baseOutput: {},
    energyConsumption: 28,
  },
  {
    id: 'spaceport',
    name: { ru: 'Космопорт', en: 'Spaceport' },
    description: {
      ru: 'Обеспечивает логистику и запуск кораблей. Необходим для флота.',
      en: 'Provides logistics and ship launching. Required for fleet operations.',
    },
    category: 'ships',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 4 }],
    baseCost: { iron: 500, carbon: 500 },
    baseTimeSec: 1200,
    baseOutput: {},
    energyConsumption: 20,
  },
  {
    id: 'shipyard',
    name: { ru: 'Верфь', en: 'Shipyard' },
    description: {
      ru: 'Позволяет строить и ремонтировать космические корабли.',
      en: 'Enables construction and repair of spacecraft.',
    },
    category: 'ships',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'spaceport', level: 1 }],
    baseCost: { iron: 800, silicon: 400 },
    baseTimeSec: 1800,
    baseOutput: {},
    energyConsumption: 40,
  },
  {
    id: 'lab',
    name: { ru: 'Лаборатория', en: 'Laboratory' },
    description: {
      ru: 'Центр научных исследований. Разблокирует новые технологии.',
      en: 'Center for scientific research. Unlocks new technologies.',
    },
    category: 'progress',
    maxPerPlanet: null,
    maxGlobal: 1,
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 3 }],
    baseCost: { iron: 300, silicon: 600 },
    baseTimeSec: 1800,
    baseOutput: {},
    energyConsumption: 30,
  },
  {
    id: 'cryo_factory',
    name: { ru: 'Криогенный завод', en: 'Cryo Factory' },
    description: {
      ru: 'Управляет криогенной переработкой воды и льда.',
      en: 'Handles cryogenic processing of water and ice.',
    },
    category: 'production',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 3 }],
    baseCost: { iron: 600, silicon: 200, magnesium: 50 },
    baseTimeSec: 2700,
    baseOutput: {},
    energyConsumption: 40,
  },
  {
    id: 'solar_plant',
    name: { ru: 'Солнечная станция', en: 'Solar Plant' },
    description: {
      ru: 'Генерирует энергию из солнечного излучения для питания базы.',
      en: 'Generates energy from solar radiation to power the base.',
    },
    category: 'energy',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 1 }],
    baseCost: { silicon: 150, iron: 50 },
    baseTimeSec: 600,
    baseOutput: { energy: 50 },
    energyConsumption: 0,
  },
  {
    id: 'wind_turbine',
    name: { ru: 'Ветротурбина', en: 'Wind Turbine' },
    description: {
      ru: 'Генерирует энергию из атмосферных потоков. Крупные планеты дают более стабильный поток.',
      en: 'Generates energy from atmospheric currents. Larger planets provide steadier output.',
    },
    category: 'energy',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 1 }],
    baseCost: { iron: 140, aluminum: 60, silicon: 60 },
    baseTimeSec: 720,
    baseOutput: { energy: 38 },
    energyConsumption: 0,
  },
  {
    id: 'fuel_generator',
    name: { ru: 'Топливный генератор', en: 'Fuel Generator' },
    description: {
      ru: 'Заряжает аккумуляторы топливом, нефтью или метаном с разной энергоотдачей.',
      en: 'Charges batteries with fuel, oil, or methane at different energy yields.',
    },
    category: 'energy',
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'command_center', level: 2 }],
    baseCost: { iron: 220, silicon: 120, steel: 80 },
    baseTimeSec: 900,
    baseOutput: {},
    energyConsumption: 0,
  },
  {
    id: 'military_shipyard',
    name: { ru: 'Военная верфь', en: 'Military Shipyard' },
    description: {
      ru: 'Специализированная верфь для строительства боевых кораблей. Требует военных материалов.',
      en: 'Specialized yard for constructing combat vessels. Requires military-grade materials.',
    },
    category: 'ships',
    maxPerPlanet: 1,
    maxGlobal: null,
    maxLevel: MAX_BUILDING_LEVEL,
    deps: [{ typeId: 'shipyard', level: 2 }],
    baseCost: { steel: 600, military_alloy: 200, military_composite: 100, electronics: 150 },
    baseTimeSec: 3600,
    baseOutput: {},
    energyConsumption: 50,
    hp: 2000,
    combatStats: { targetClass: 'building' } as CombatStats,
  },
];

export const SHIP_TYPE_CATALOG_ROWS: ShipCatalogRow[] = [
  {
    id: 'scout',
    name: { ru: 'Разведчик', en: 'Scout' },
    role: 'recon',
    hp: 40,
    speed: '2.00',
    cargo: 50,
    dps: 0,
    armor: 0,
    fuelConsumption: '0.30',
    fuelCapacity: 200,
    jumpFuelCapacity: 3,
    buildTimeSec: 600,
    buildCost: { iron: 100, silicon: 50, fuel: 30 },
    requiredBuildings: [{ typeId: 'shipyard', level: 1 }],
    sensorRange: 30,
    combatStats: { targetClass: 'civilian' } as CombatStats,
  },
  {
    id: 'cargo_light',
    name: { ru: 'Лёгкий транспорт', en: 'Lightweight Transporter' },
    role: 'logistics',
    hp: 60,
    speed: '1.20',
    cargo: 5000,
    dps: 0,
    armor: 0,
    fuelConsumption: '0.80',
    fuelCapacity: 100,
    jumpFuelCapacity: 4,
    buildTimeSec: 1200,
    buildCost: { iron: 500, silicon: 300, carbon: 200, methane: 100 },
    requiredBuildings: [{ typeId: 'shipyard', level: 2 }],
    sensorRange: 8,
    combatStats: { targetClass: 'civilian' } as CombatStats,
  },
  {
    id: 'colonizer',
    name: { ru: 'Колонизатор', en: 'Colonizer' },
    role: 'colonization',
    hp: 120,
    speed: '1.00',
    cargo: 1,
    dps: 0,
    armor: 0,
    fuelConsumption: '1.50',
    fuelCapacity: 80,
    jumpFuelCapacity: 4,
    buildTimeSec: 14400,
    buildCost: { steel: 2500, silicon: 800, biomass: 400 },
    requiredBuildings: [{ typeId: 'shipyard', level: 1 }],
    sensorRange: 10,
    combatStats: { targetClass: 'civilian' } as CombatStats,
  },
  {
    id: 'recon_probe',
    name: { ru: 'Разведывательный зонд', en: 'Recon Probe' },
    role: 'exploration',
    hp: 20,
    speed: '4.00',
    cargo: 0,
    dps: 0,
    armor: 0,
    fuelConsumption: '0.10',
    fuelCapacity: 50,
    jumpFuelCapacity: 3,
    buildTimeSec: 300,
    buildCost: { silicon: 40, fuel: 20, electronics: 10 },
    requiredBuildings: [{ typeId: 'shipyard', level: 1 }],
    sensorRange: 60,
    combatStats: { targetClass: 'civilian' } as CombatStats,
  },
  {
    id: 'refueler',
    name: { ru: 'Заправщик', en: 'Refueler' },
    role: 'support',
    hp: 80,
    speed: '1.00',
    cargo: 200,
    dps: 0,
    armor: 5,
    fuelConsumption: '1.00',
    fuelCapacity: 500,
    jumpFuelCapacity: 20,
    buildTimeSec: 3600,
    buildCost: { steel: 400, iron: 300, electronics: 100, fuel: 100 },
    requiredBuildings: [{ typeId: 'shipyard', level: 2 }],
    sensorRange: 10,
    combatStats: { targetClass: 'civilian' } as CombatStats,
  },
  {
    id: 'fighter',
    name: { ru: 'Истребитель', en: 'Fighter' },
    role: 'combat',
    hp: 400,
    speed: '3.00',
    cargo: 0,
    dps: 50,
    armor: 10,
    fuelConsumption: '0.50',
    fuelCapacity: 150,
    jumpFuelCapacity: 6,
    buildTimeSec: 1800,
    buildCost: { iron: 300, silicon: 200, fuel: 50 },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 1 }],
    sensorRange: 20,
    combatStats: {
      targetClass: 'military_light',
      damageProfile: { damageType: 'kinetic', dps: 50, armorPenetration: 0.25, shieldMultiplier: 1.0 },
      engagementRange: 'medium',
      armor: 10,
      evasion: 0.2,
    } as CombatStats,
  },
  {
    id: 'cruiser',
    name: { ru: 'Крейсер', en: 'Cruiser' },
    role: 'combat',
    hp: 1500,
    speed: '1.50',
    cargo: 500,
    dps: 200,
    armor: 50,
    fuelConsumption: '2.00',
    fuelCapacity: 300,
    jumpFuelCapacity: 8,
    buildTimeSec: 7200,
    buildCost: { steel: 1000, electronics: 300, fuel: 200 },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 3 }],
    sensorRange: 40,
    combatStats: {
      targetClass: 'military_medium',
      damageProfile: { damageType: 'kinetic', dps: 200, armorPenetration: 0.35, shieldMultiplier: 1.0 },
      engagementRange: 'medium',
      armor: 50,
      evasion: 0.06,
    } as CombatStats,
  },
  {
    id: 'battleship',
    name: { ru: 'Линкор', en: 'Battleship' },
    role: 'combat',
    hp: 5000,
    speed: '1.00',
    cargo: 1000,
    dps: 800,
    armor: 150,
    fuelConsumption: '5.00',
    fuelCapacity: 600,
    jumpFuelCapacity: 10,
    buildTimeSec: 28800,
    buildCost: { steel: 4000, electronics: 1500, jump_fuel: 10 },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 5 }],
    sensorRange: 60,
    combatStats: {
      targetClass: 'military_heavy',
      damageProfile: { damageType: 'kinetic', dps: 800, armorPenetration: 0.45, shieldMultiplier: 1.0 },
      engagementRange: 'long',
      armor: 150,
      evasion: 0.01,
    } as CombatStats,
  },
  {
    id: 'light_fighter',
    name: { ru: 'Лёгкий истребитель', en: 'Light Fighter' },
    role: 'combat',
    hp: 200,
    speed: '4.00',
    cargo: 0,
    dps: 30,
    armor: 5,
    fuelConsumption: '0.40',
    fuelCapacity: 100,
    jumpFuelCapacity: 5,
    buildTimeSec: 1200,
    buildCost: { iron: 200, silicon: 150, fuel: 30 },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 1 }],
    sensorRange: 15,
    combatStats: {
      targetClass: 'military_light',
      damageProfile: { damageType: 'kinetic', dps: 30, armorPenetration: 0.2, shieldMultiplier: 1.0 },
      engagementRange: 'close',
      armor: 5,
      evasion: 0.4,
    } as CombatStats,
  },
  {
    id: 'light_bomber',
    name: { ru: 'Лёгкий бомбардировщик', en: 'Light Bomber' },
    role: 'combat',
    hp: 350,
    speed: '1.80',
    cargo: 0,
    dps: 100,
    armor: 20,
    fuelConsumption: '1.20',
    fuelCapacity: 200,
    jumpFuelCapacity: 8,
    buildTimeSec: 3600,
    buildCost: { steel: 600, military_alloy: 100, electronics: 150, fuel: 80 },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 2 }],
    sensorRange: 12,
    combatStats: {
      // `targetClass` describes what this hull looks like *as a defender* — a
      // bomber is a military_light ship, so other ships can attack it. Its
      // own ground-attack payload is described by damageProfile + orbital
      // engagementRange, which `combat/engine.ts` routes to surface targets
      // instead of opposing ships.
      targetClass: 'military_light',
      damageProfile: { damageType: 'explosive', dps: 100, armorPenetration: 0.1, shieldMultiplier: 0.5 },
      engagementRange: 'orbital',
      armor: 20,
      evasion: 0.12,
    } as CombatStats,
  },
  {
    id: 'light_laser',
    name: { ru: 'Лёгкий лазерный корабль', en: 'Light Laser Ship' },
    role: 'combat',
    hp: 280,
    speed: '2.50',
    cargo: 0,
    dps: 60,
    armor: 8,
    fuelConsumption: '0.80',
    fuelCapacity: 150,
    jumpFuelCapacity: 6,
    buildTimeSec: 2700,
    buildCost: { steel: 400, silicon: 200, liquid_nitrogen: 50, electronics: 120 },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 2 }],
    sensorRange: 25,
    combatStats: {
      targetClass: 'military_light',
      damageProfile: { damageType: 'energy', dps: 60, armorPenetration: 0.4, shieldMultiplier: 1.5 },
      engagementRange: 'long',
      armor: 8,
      evasion: 0.22,
    } as CombatStats,
  },
  {
    id: 'small_shield_ship',
    name: { ru: 'Малый щитовой корабль', en: 'Small Shield Ship' },
    role: 'shield',
    hp: 320,
    speed: '2.20',
    cargo: 0,
    dps: 0,
    armor: 18,
    fuelConsumption: '0.90',
    fuelCapacity: 180,
    jumpFuelCapacity: 6,
    buildTimeSec: 4200,
    buildCost: {
      steel: 700,
      electronics: 180,
      military_composite: 80,
      liquid_nitrogen: 60,
      fuel: 80,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 2 }],
    sensorRange: 18,
    combatStats: {
      targetClass: 'military_light',
      armor: 18,
      evasion: 0.16,
      shields: {
        capacity: 700,
        currentHp: 700,
        radius: 1.5,
        rechargeRate: 18,
        delayAfterDamageSec: 10,
        downtimeSec: 20,
        state: 'active',
      },
    } as CombatStats,
  },
  {
    id: 'medium_fighter',
    name: { ru: 'Средний истребитель', en: 'Medium Fighter' },
    role: 'combat',
    hp: 650,
    speed: '3.20',
    cargo: 0,
    dps: 90,
    armor: 28,
    fuelConsumption: '0.90',
    fuelCapacity: 220,
    jumpFuelCapacity: 8,
    buildTimeSec: 5400,
    buildCost: {
      steel: 900,
      military_alloy: 220,
      military_composite: 80,
      electronics: 180,
      titanium: 80,
      fuel: 120,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 3 }],
    sensorRange: 22,
    combatStats: {
      targetClass: 'military_medium',
      damageProfile: { damageType: 'kinetic', dps: 90, armorPenetration: 0.3, shieldMultiplier: 1.0 },
      engagementRange: 'medium',
      armor: 28,
      evasion: 0.22,
    } as CombatStats,
  },
  {
    id: 'medium_bomber',
    name: { ru: 'Средний бомбардировщик', en: 'Medium Bomber' },
    role: 'combat',
    hp: 900,
    speed: '1.50',
    cargo: 0,
    dps: 210,
    armor: 55,
    fuelConsumption: '2.00',
    fuelCapacity: 350,
    jumpFuelCapacity: 12,
    buildTimeSec: 9000,
    buildCost: {
      steel: 1600,
      military_alloy: 350,
      military_composite: 180,
      electronics: 260,
      titanium: 160,
      sulfur: 120,
      fuel: 220,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 3 }],
    sensorRange: 16,
    combatStats: {
      targetClass: 'military_medium',
      damageProfile: { damageType: 'explosive', dps: 210, armorPenetration: 0.16, shieldMultiplier: 0.55 },
      engagementRange: 'orbital',
      armor: 55,
      evasion: 0.08,
    } as CombatStats,
  },
  {
    id: 'medium_laser',
    name: { ru: 'Средний лазерный корабль', en: 'Medium Laser Ship' },
    role: 'combat',
    hp: 750,
    speed: '2.10',
    cargo: 0,
    dps: 130,
    armor: 35,
    fuelConsumption: '1.40',
    fuelCapacity: 260,
    jumpFuelCapacity: 10,
    buildTimeSec: 7200,
    buildCost: {
      steel: 1100,
      silicon_carbide: 80,
      liquid_nitrogen: 130,
      electronics: 320,
      cobalt: 90,
      jump_fuel: 2,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 3 }],
    sensorRange: 34,
    combatStats: {
      targetClass: 'military_medium',
      damageProfile: { damageType: 'energy', dps: 130, armorPenetration: 0.55, shieldMultiplier: 1.6 },
      engagementRange: 'long',
      armor: 35,
      evasion: 0.14,
    } as CombatStats,
  },
  {
    id: 'medium_shield_ship',
    name: { ru: 'Средний щитовой корабль', en: 'Medium Shield Ship' },
    role: 'shield',
    hp: 950,
    speed: '1.60',
    cargo: 0,
    dps: 0,
    armor: 60,
    fuelConsumption: '1.80',
    fuelCapacity: 360,
    jumpFuelCapacity: 12,
    buildTimeSec: 9600,
    buildCost: {
      steel: 1900,
      military_alloy: 320,
      military_composite: 260,
      electronics: 420,
      silicon_carbide: 100,
      cobalt: 120,
      jump_fuel: 3,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 4 }],
    sensorRange: 28,
    combatStats: {
      targetClass: 'military_medium',
      armor: 60,
      evasion: 0.08,
      shields: {
        capacity: 1800,
        currentHp: 1800,
        radius: 3.5,
        rechargeRate: 35,
        delayAfterDamageSec: 15,
        downtimeSec: 30,
        state: 'active',
      },
    } as CombatStats,
  },
  {
    id: 'heavy_fighter',
    name: { ru: 'Тяжёлый истребитель', en: 'Heavy Fighter' },
    role: 'combat',
    hp: 1500,
    speed: '2.40',
    cargo: 0,
    dps: 220,
    armor: 80,
    fuelConsumption: '2.20',
    fuelCapacity: 450,
    jumpFuelCapacity: 14,
    buildTimeSec: 14400,
    buildCost: {
      steel: 2800,
      military_alloy: 650,
      military_composite: 320,
      electronics: 520,
      titanium: 420,
      cobalt: 160,
      jump_fuel: 5,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 5 }],
    sensorRange: 30,
    combatStats: {
      targetClass: 'military_heavy',
      damageProfile: { damageType: 'kinetic', dps: 220, armorPenetration: 0.4, shieldMultiplier: 1.0 },
      engagementRange: 'medium',
      armor: 80,
      evasion: 0.1,
    } as CombatStats,
  },
  {
    id: 'heavy_bomber',
    name: { ru: 'Тяжёлый бомбардировщик', en: 'Heavy Bomber' },
    role: 'combat',
    hp: 2100,
    speed: '1.10',
    cargo: 0,
    dps: 420,
    armor: 140,
    fuelConsumption: '4.00',
    fuelCapacity: 650,
    jumpFuelCapacity: 18,
    buildTimeSec: 21600,
    buildCost: {
      steel: 4200,
      military_alloy: 900,
      military_composite: 520,
      electronics: 700,
      titanium: 520,
      iridium: 40,
      jump_fuel: 8,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 5 }],
    sensorRange: 20,
    combatStats: {
      targetClass: 'military_heavy',
      damageProfile: { damageType: 'explosive', dps: 420, armorPenetration: 0.22, shieldMultiplier: 0.6 },
      engagementRange: 'orbital',
      armor: 140,
      evasion: 0.03,
    } as CombatStats,
  },
  {
    id: 'heavy_laser',
    name: { ru: 'Тяжёлый лазерный корабль', en: 'Heavy Laser Ship' },
    role: 'combat',
    hp: 1800,
    speed: '1.60',
    cargo: 0,
    dps: 300,
    armor: 100,
    fuelConsumption: '3.00',
    fuelCapacity: 520,
    jumpFuelCapacity: 16,
    buildTimeSec: 18000,
    buildCost: {
      steel: 3600,
      silicon_carbide: 260,
      liquid_nitrogen: 320,
      electronics: 900,
      cobalt: 240,
      iridium: 30,
      jump_fuel: 6,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 5 }],
    sensorRange: 48,
    combatStats: {
      targetClass: 'military_heavy',
      damageProfile: { damageType: 'energy', dps: 300, armorPenetration: 0.7, shieldMultiplier: 1.75 },
      engagementRange: 'long',
      armor: 100,
      evasion: 0.06,
    } as CombatStats,
  },
  {
    id: 'large_shield_ship',
    name: { ru: 'Большой щитовой корабль', en: 'Large Shield Ship' },
    role: 'shield',
    hp: 2200,
    speed: '1.00',
    cargo: 0,
    dps: 0,
    armor: 145,
    fuelConsumption: '4.20',
    fuelCapacity: 720,
    jumpFuelCapacity: 22,
    buildTimeSec: 24000,
    buildCost: {
      steel: 4800,
      military_alloy: 900,
      military_composite: 700,
      electronics: 1000,
      silicon_carbide: 260,
      iridium: 80,
      antimatter: 6,
      jump_fuel: 12,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 6 }],
    sensorRange: 44,
    combatStats: {
      targetClass: 'military_heavy',
      armor: 145,
      evasion: 0.02,
      shields: {
        capacity: 4200,
        currentHp: 4200,
        radius: 6,
        rechargeRate: 70,
        delayAfterDamageSec: 20,
        downtimeSec: 45,
        state: 'active',
      },
    } as CombatStats,
  },
  {
    id: 'rocket_carrier',
    name: { ru: 'Ракетный носитель', en: 'Rocket Carrier' },
    role: 'missile',
    hp: 1100,
    speed: '1.20',
    cargo: 0,
    dps: 50,
    armor: 75,
    fuelConsumption: '3.00',
    fuelCapacity: 600,
    jumpFuelCapacity: 20,
    buildTimeSec: 14400,
    buildCost: {
      steel: 2500,
      military_composite: 500,
      electronics: 650,
      cobalt: 200,
      sulfur: 260,
      jump_fuel: 10,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 4 }],
    sensorRange: 44,
    combatStats: {
      targetClass: 'military_medium',
      engagementRange: 'long',
      armor: 75,
      evasion: 0.02,
      missilePayload: {
        damageType: 'explosive',
        alphaDamage: 1500,
        reloadSec: 30,
        armorPenetration: 0.35,
        shieldMultiplier: 0.8,
        validTargetClasses: ['military_medium', 'military_heavy'],
        evasionCounterThreshold: 0.3,
        maxRange: 'long',
      },
    } as CombatStats,
  },
  {
    id: 'heavy_rocket_carrier',
    name: { ru: 'Тяжёлый ракетный носитель', en: 'Heavy Rocket Carrier' },
    role: 'missile',
    hp: 2600,
    speed: '0.90',
    cargo: 0,
    dps: 92,
    armor: 160,
    fuelConsumption: '5.50',
    fuelCapacity: 850,
    jumpFuelCapacity: 28,
    buildTimeSec: 28800,
    buildCost: {
      steel: 5200,
      military_composite: 900,
      electronics: 1200,
      cobalt: 420,
      iridium: 80,
      antimatter: 8,
      jump_fuel: 18,
    },
    requiredBuildings: [{ typeId: 'military_shipyard', level: 6 }],
    sensorRange: 60,
    combatStats: {
      targetClass: 'military_heavy',
      engagementRange: 'long',
      armor: 160,
      evasion: 0.01,
      missilePayload: {
        damageType: 'explosive',
        alphaDamage: 3300,
        reloadSec: 36,
        armorPenetration: 0.45,
        shieldMultiplier: 0.85,
        validTargetClasses: ['military_medium', 'military_heavy'],
        evasionCounterThreshold: 0.25,
        maxRange: 'long',
      },
    } as CombatStats,
  },
];
